### ISSUE TITLE
README.md unclear on what environment variables do

### ISSUE THREAD

**Issue by WilliamTheMarsman** [prodrigestivill/docker-postgres-backup-local#11]
## Description

The README doesn't mention what environment variables are used for. I looked through the bash script, and it appears these are three directories which are populated with hardlinks to the database backups, so that days, weeks and months can be pruned properly. 

I didn't understand how hardlinks worked until I read this source code, so it may be worth including a section in the README which goes over all of the environment variables flags so others do not need to read the script in order to understand how it works. I've made an example table below.

## Environment Variables

Since there is already an example yaml, I have left out example values.

| env variable | description |
|--|--|
| POSTGRES_HOST | postgres connection parameter; postgres host |
| POSTGRES_DB | postgres connection parameter; postgres database to connect to |
| POSTGRES_USER | postgres connection parameter; postgres user to connect with |
| POSTGRES_PASSWORD | postgres connection parameter; postgres password to connect with |
| POSTGRES_PASSWORD_FILE | alternative to POSTGRES_PASSWORD, to use with docker secrets |
| POSTGRES_EXTRA_OPTS | additional options to supply `pg_dump` when creating back-ups |
| SCHEDULE | cron-schedule specifying the interval between taking postgres backups |
| BACKUP_KEEP_DAYS | number of days to keep backups before removing |
| BACKUP_KEEP_WEEKS | number of weeks to keep backups before removing |
| BACKUP_KEEP_MONTHS | number of months to keep backups before removing |
| HEALTHCHECK_PORT | *I don't know how this is used, but I am assuming this provides a health-check endpoint* |

**Comment by dargmuesli** [comment]
The `BACKUP_KEEP_...` variables' descriptions are somewhat overlapping/misleading, I think. Shouldn't it be phrased `number of [daily|weekly|monthly] backups to keep before removal`?

**Comment by prodrigestivill** [comment]
fixed, thanks.
