### ISSUE TITLE
curl can only be used on the alpine image because of missing ca certificates

### ISSUE THREAD

**Issue by snyssen** [prodrigestivill/docker-postgres-backup-local#119]
The [Debian Dockerfile](https://github.com/prodrigestivill/docker-postgres-backup-local/blob/main/debian.Dockerfile#L25) explicitely removes the ca-certificates package as part of its build, which means curl cannot be used for healtchecks as it returns the following error due to missing ca certificates:

```sh
curl: (77) error setting certificate verify locations: CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs
```

This is not an issue with the Alpine image since the ca certificates are not removed from that image. Simply removing the offending line in the Debian build should be enough.

**Comment by prodrigestivill** [comment]
Thanks for the report.
