### ISSUE TITLE
try to restore and get error: psql: error: connection to server on socket

### ISSUE THREAD

**Issue by hiepxanh** [prodrigestivill/docker-postgres-backup-local#130]
the context is, I try to restore the postgres database:

## command use:
docker -c sun exec --tty --interactive production-database-pgbackups-1 sh -c "zcat /backups/last/awread_database-latest.sql.gz | psql --username=postgres --dbname=awread-database"

## error name 

psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?

![image](https://user-images.githubusercontent.com/16970990/228688273-7701e890-6dd0-44e8-a7f5-5e6954e30a75.png)

# answer:
 By default psql is trying to connect to server using UNIX socket.
 indeed I need to add --host or -h to restore command

docker -c sun exec --tty --interactive production-database-pgbackups-1 sh -c "zcat /backups/last/awread_database-latest.sql.gz | psql --username=postgres --dbname=awread-database --host=postgres"

https://stackoverflow.com/a/52442893/5748537

**Comment by prodrigestivill** [comment]
README.md already states you need to add `--host` on restore.

**Comment by hiepxanh** [comment]
Yes you are right
