### ISSUE TITLE
Backup doesn't work with password provided by secret

### ISSUE THREAD

**Issue by adriannowak** [prodrigestivill/docker-postgres-backup-local#142]
Hey,

Backup.sh produces an error message even if the property POSTGRES_PASSWORD_FILE is set.

```
3b84769e4cce:/# ./backup.sh
Missing POSTGRES_PASSWORD_FILE or POSTGRES_PASSFILE_STORE file.
3b84769e4cce:/# env | grep POSTGRES_PASSWORD_FILE
POSTGRES_PASSWORD_FILE=/run/secrets/trainings-db-username
3b84769e4cce:/# ls /run/secrets/trainings-db-username
/run/secrets/trainings-db-username
```

Tested with `13-alpine`

**Comment by prodrigestivill** [comment]
Did you check the file permissions, the file must be redeablr by the user running the script.

**Comment by adriannowak** [comment]
Yes I did, the file exists, and I have the rights to read it

**Comment by adriannowak** [comment]
Seems only `-alpine` is affected. After switching to Debian release, everything has started working as expected. 
Most likely, "test" command works a bit differently there.

**Comment by prodrigestivill** [comment]
I tried locally and couldn't replicate your issue.

Can you confirm the exact alpine tag or the sha256 docker digest you are using?

**Comment by prodrigestivill** [comment]
Please reopen if you are still having issues.

**Comment by Haeri** [comment]
Had a similar issue where `POSTGRES_PASSWORD_FILE` was set but calling `./backup.sh` gave me the following error:

```
pg_dump: error: connection to server at "database" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
```

I found out that I had a linebreak at the very end of the password file which was causing the problem. Documenting this for future generations.
