### ISSUE TITLE
POSTGRES_DB is required, even with POSTGRES_CLUSTER

### ISSUE THREAD

**Issue by mmomjian** [prodrigestivill/docker-postgres-backup-local#149]
It seems this was discussed in #85 but closed w/ no resolution.

Based on the documentation and testing at [immich-app/immich/8939](https://github.com/immich-app/immich/pull/8939), `POSTGRES_DB` is required even with `POSTGRES_CLUSTER=TRUE`. Since `POSTGRES_CLUSTER` uses `pg_dumpall`, `POSTGRES_DB` should not be compatible with this setting.

Currently, an error is thrown if `POSTGRES_DB` is not specified. In some cases the database name may not be known, this should not prevent a backup of the entire cluster.

Resolution: `POSTGRES_DB` and `POSTGRES_CLUSTER` env vars should be mutually exclusive, as --dbname is ignored. 

```
--dbname=connstr
Specifies parameters used to connect to the server, as a connection string; these will override any conflicting command line options.

The option is called --dbname for consistency with other client applications, but because pg_dumpall needs to connect to many databases, the database name in the connection string will be ignored. Use the -l option to specify the name of the database used for the initial connection, which will dump global objects and discover what other databases should be dumped.

-l dbname
--database=dbname
Specifies the name of the database to connect to for dumping global objects and discovering what other databases should be dumped. If not specified, the postgres database will be used, and if that does not exist, template1 will be used.


```

**Comment by prodrigestivill** [comment]
Hello @mmomjian,

The `POSTGRES_DB` is used to specify the `-l dbname` when `POSTGRES_CLUSTER=TRUE`, not the `--dbname`.

So copying from your descriptions it would mean:
> Specifies the name of the database to connect to for dumping global objects and discovering what other databases should be dumped. If not specified, the postgres database will be used, and if that does not exist, template1 will be used.

I understand that this issue means the README file cloud be improved regarding the description of this variable in this cases.
I think that leaving it mandatory is still useful, better define a specific the behavior instead of relying on the internal checks, but I'm open to read your objections or recommendations.

Does this information help?
Can you propose a better description for the field that fits in the configuration table?

**Comment by mmomjian** [comment]
Thanks for the reply. I would propose that the description for `POSTGRES_DB` be added something like: "when `POSTGRES_CLUSTER` is set, all databases will be backed up, and `POSTGRES_D` specifies the database that `pg_dumpall` will connect to." I can open a PR if you prefer.

Leaving it as mandatory is reasonable, while `pg_dumpall` does have its own set of defaults (postgres -> template1), and we would not be able to specify a fallback like that with an env var, it seems likely both of those databases will be present in almost all instances.

**Comment by prodrigestivill** [comment]
Thanks for reporting, I hope the updated description is enough.

I also tried to change it to not mandatory, but it requires a major refactor that I don't feel it would compensate the risks for this issue.

**Comment by mmomjian** [comment]
Thanks for adding the docs, that helps.
