### ISSUE TITLE
Backup the entire database cluster

### ISSUE THREAD

**Issue by SamyOteroGlez** [prodrigestivill/docker-postgres-backup-local#30]
Hi all,

It would be nice if you could add an option to backup the entire database cluster, so you could get all the roles and permissions in the backup as well.

Something like this:
```
pg_dumpall -v -h <db.host.address> -p <db.host.port> -U <db.user> -f "<path/to/the/backup/file.sql>"
```

Cheers,

Sam

**Comment by prodrigestivill** [comment]
Please test the latest version uploaded today using the new options `POSTGRES_CLUSTER` and `POSTGRES_PASSFILE_STORE` and reopen the issue if it doesn't work as desired.
