### ISSUE TITLE
Problem with cluster feature

### ISSUE THREAD

**Issue by ThE-MaRaC** [prodrigestivill/docker-postgres-backup-local#31]
We are trying to setup periodic backup with the following configuration
```
environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_DB=postgres://postgres:5432 (pg_dumpall needs connection string)
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_EXTRA_OPTS=
    - POSTGRES_CLUSTER=TRUE
    - SCHEDULE=@every 5m
    - BACKUP_KEEP_DAYS=7
    - BACKUP_KEEP_WEEKS=4
    - BACKUP_KEEP_MONTHS=6
    - BACKUP_SUFFIX=.sql
```
DB server is PostgreSQL 9.5
```
root@a6fe2d177a0b:/# postgres -V
postgres (PostgreSQL) 9.5.23
```
But, whenever backup runs the following error is reported:
```
postgres-backup    | 2020/09/01 07:25:40 14: Creating pg_dumpall of postgres://postgres:5432 database from postgres...
postgres-backup    | 2020/09/01 07:25:40 14: pg_dumpall: could not open the output file "/backups/daily/postgres://postgres:5432-20200901-072540.sql": No such file or directory
```
Am I missing something?

**Comment by prodrigestivill** [comment]
We haven't tested this feature yet, maybe #30 was closed too soon.

But, acording to the official documentation of [pg_dumpall](https://www.postgresql.org/docs/12/app-pg-dumpall.html), `--database` (POSTGRES_DB) is not a connection string:
> Specifies the name of the database to connect to to dump global objects and discover what other databases should be dumped. If not specified, the postgres database will be used, and if that does not exist, template1 will be used.

Can you try out only specifying the connection database name?

**Comment by ThE-MaRaC** [comment]
Already tried and this is the error that I got:
```
pg_dumpall: missing "=" after "postgres" in connection info string
```
I am using PostgreSQL 9.5, so maybe this is the reason why I have:
```
-d connstr
--dbname=connstr
Specifies parameters used to connect to the server, as a connection string. See Section 31.1.1 for more information.

The option is called --dbname for consistency with other client applications, but because pg_dumpall needs to connect to many databases, database name in the connection string will be ignored. Use -l option to specify the name of the database used to dump global objects and to discover what other databases should be dumped.
```
Check here: https://www.postgresql.org/docs/9.5/app-pg-dumpall.html

**Comment by ThE-MaRaC** [comment]
Additionally, --database is used for global data export and to discover a list of DBS which have to be exported.
-d, --dbname (POSTGRES_DB) is relevant for export and even in the latest version this is a connection string.

**Comment by prodrigestivill** [comment]
Yes, it looks it was a missundestaning between `--dbname` (`-d`) and `--database` (`-l`).

Changed to use `-l` for `pg_dumpall` and `-d` for `pg_dump`.
Now it should work setting `POSTGRES_DB` to the connection DB.
Alternatively, if `--dbname` is required for your setup, you can specify it inside `POSTGRES_EXTRA_OPTS`.

Can you please test it with any of the recently uploaded images, and leave here your feedback. Thanks.

**Comment by ThE-MaRaC** [comment]
Now it works, here is the test configuration that we used
```
    environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_CLUSTER=TRUE
        - POSTGRES_EXTRA_OPTS=-d postgres://postgres:5432
        - SCHEDULE=@every 5m
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - BACKUP_SUFFIX=.sql
```
And backup log
```
postgres-backup    | 2020/09/01 18:12:58 14 cmd: /backup.sh
postgres-backup    | 2020/09/01 18:12:58 14: Creating cluster dump of postgres database from postgres...
postgres-backup    | 2020/09/01 18:13:00 14: '/backups/weekly/postgres-202036.sql' => '/backups/daily/postgres-20200901-181258.sql'
postgres-backup    | 2020/09/01 18:13:00 14: '/backups/monthly/postgres-202009.sql' => '/backups/daily/postgres-20200901-181258.sql'
postgres-backup    | 2020/09/01 18:13:00 14: Cleaning older than 7 days for postgres database from postgres...
postgres-backup    | 2020/09/01 18:13:00 14: SQL backup created successfully
```
It would be nice if the resulting SQL file can be compressed because this feature is missing in pg_dumpall.
Thx for your support.

**Comment by prodrigestivill** [comment]
Added compression for `pg_dumpall`, please pull latest image and remove `BACKUP_SUFFIX` from your configuration.

Feel free to reopen the issue if anything rises after this fix.
