### ISSUE TITLE
Reconsider use of gzip -9

### ISSUE THREAD

**Issue by jh-chrysos** [prodrigestivill/docker-postgres-backup-local#43]
https://github.com/prodrigestivill/docker-postgres-backup-local/blob/cddefe160b74bb16ae3915bdbbdba4288b741dd4/backup.sh#L75

In my tests, gzip -9 results in around a 7% saving in file size, but almost 3x cost in execution time.

Ideally it would be configurable.

```
no compression:
real    7m7.690s
user    0m14.668s
sys     1m3.074s

gzip (default):
real    24m0.328s
user    23m14.971s
sys     1m13.967s

gzip -9:
real    70m26.249s
user    70m6.240s
sys     1m26.190s

-rw-r--r--. 1 root root 43153842570 Feb 18 01:41 dump.sql
-rw-r--r--. 1 root root  5249807591 Feb 18 02:05 dump.sql.default.gz
-rw-r--r--. 1 root root  4933680154 Feb 18 03:16 dump.sql.minus9.gz

```

**Comment by prodrigestivill** [comment]
Thanks for the proposal.

Fixed and uploaded new versions.

**Comment by jh-chrysos** [comment]
Doesn't passing the -Z option to pg_dumpall mean it's compressing, and then you call gzip on the output again?
