### ISSUE TITLE
Change time zone

### ISSUE THREAD

**Issue by steakhutzeee** [prodrigestivill/docker-postgres-backup-local#50]
Hi,

Is it possible to change the time zone for this container? 

Thanks!

**Comment by TheSaM07** [comment]
You might want to add something like this in your docker-compose : 

    environment:
      TZ: "Europe/Paris"

Choose the Timezone that fits your need.

**Comment by steakhutzeee** [comment]
> 
> 
> You might want to add something like this in your docker-compose :
> 
> ```
> environment:
>   TZ: "Europe/Paris"
> ```
> 
> Choose the Timezone that fits your need.

I confirm that this works. Maybe could be good to add this to the container description.

Thanks again!
