### ISSUE TITLE
Restore: the input is not a TTY

### ISSUE THREAD

**Issue by acouvreur** [prodrigestivill/docker-postgres-backup-local#54]
When trying to restore a backup to a remote server:
`zcat backupfile.sql.gz | docker run --rm --tty --interactive postgres:$VERSION psql --host=$HOSTNAME --port=$PORT --username=$USERNAME --dbname=$DBNAME -W`

When replacing all the variables, I get the following error:
`the input is not a TTY`

I cannot restore my backup using the command you provided. I am using ubuntu 20.10 with docker version 20.10.2.
Is there something that I am doing wrong ?

**Comment by prodrigestivill** [comment]
Please try this and give us feedback:
```sh
docker run --rm --tty --interactive -v $BACKUPFILE:/tmp/backupfile.sql.gz postgres:$VERSION /bin/sh -c "zcat /tmp/backupfile.sql.gz | psql --host=$HOSTNAME --port=$PORT --username=$USERNAME --dbname=$DBNAME -W"
```

**Comment by acouvreur** [comment]
Can confirm that it works! The README should be updated I think.

**Comment by Jogai** [comment]
I get an error with that command too:

```
docker run --rm --tty --interactive -v $BACKUPFILE:/Project/MyDBase-20211019-070719.sql.gz postgres:14 /bin/sh -c "zcat /Projects/MyDBase-20211019-070719.sql.gz | psql --host=pg-db-server --port=5432 --username=postgres --dbname=Restore -W"

docker: Error response from daemon: failed to create shim: OCI runtime create failed: invalid mount {Destination::/Project/MyDBase-20211019-070719.sql.gz Type:bind Source:/var/lib/docker/volumes/cb4f9f8f2265db272612ec79d021dffa4af959e06f5cbbbee1bc1977212fa0ba/_data Options:[rbind]}: mount destination :/Project/MyDBase-20211019-070719.sql.gz not absolute: unknown.
