### ISSUE TITLE
Backup not running

### ISSUE THREAD

**Issue by Glideh** [prodrigestivill/docker-postgres-backup-local#68]
Thank you for this great image ! This is a quite clever piece of assembly.

Here is a composition which does not seem to run the backup script:

```yml
version: '3.5'

services:
  db:
    image: postgres:13.6-alpine3.15
    env_file:
      - .env_db
  backup:
    image: prodrigestivill/postgres-backup-local:13-alpine
    volumes:
      - ./backups:/backups
    depends_on:
      - db
    env_file:
      - .env_db
    environment:
      - POSTGRES_HOST=db
      - SCHEDULE="@every 1m"
```

`env_db` contains my `POSTGRES_USER`, `POSTGRES_DB` & `POSTGRES_PASSWORD` variables

Startup log says:

```
2022/03/17 12:16:29 Running version: v0.0.10
2022/03/17 12:16:29 new cron: "@every 1m"
2022/03/17 12:16:29 Opening port 8080 for health checking
```

Nothing else after that and no backup created.

However trying manually (from the container `sh`)

```
/ # go-cron -s "* * * * *" -p 0 -- echo "test"
2022/03/17 14:08:35 Running version: v0.0.10
2022/03/17 14:08:35 new cron: * * * * *
2022/03/17 14:09:00 545 cmd: echo test
2022/03/17 14:09:00 545: test
2022/03/17 14:10:00 546 cmd: echo test
2022/03/17 14:10:00 546: test
```

_Also working with the backup script_
Can someone help me to debug that ?
Why the cron is not running from the composition ?

**Comment by Glideh** [comment]
Because you need to remove the " around the SCHEDULE on the composition:
`SCHEDULE=@every 1m` instead of `SCHEDULE="@every 1m"`

Would be great to have an expression validator logging the error though, I'll suggest that in the `go-cron` proj if not already existing

**Comment by prodrigestivill** [comment]
Hello @Glideh,

I believe that what you are exposing is related with the docker compose YAML format, and not with `go-cron`.
You can use "" only if you use an YAML object for environment keys instead of an array.

Please check the [docker-compose official documentation](https://docs.docker.com/compose/compose-file/compose-file-v2/#environment) for more information.
